AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'This function is invoked by AWS CloudWatch events in response to state
  change in your AWS resources which matches a event target definition. The event
  payload received is then forwarded to Sumo Logic HTTP source endpoint.

  '
Globals:
  Function:
    Timeout: 300
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Sumo Logic Deployment Configuration
      Parameters:
      - SumoDeployment
      - SumoAccessID
      - SumoAccessKey
    - Label:
        default: Collection Configuration
      Parameters:
      - CollectorName
      - SourceName
      - SourceCategoryName
      - RemoveSumoResourcesOnDeleteStack
    ParameterLabels:
      SumoDeployment:
        default: Deployment Name
      SumoAccessID:
        default: Access ID
      SumoAccessKey:
        default: Access Key
      CollectorName:
        default: Collector Name
      SourceName:
        default: Source Name
      SourceCategoryName:
        default: Source Category Name
      RemoveSumoResourcesOnDeleteStack:
        default: Remove Sumo Resources On Delete Stack
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This function is invoked by AWS CloudWatch events in response to
      state change in your AWS resources which matches a event target definition.
      The event payload received is then forwarded to Sumo Logic HTTP source endpoint.
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - sumologic
    - serverless
    - guarddutybenchmark
    - security
    - benchmark
    - guardduty
    Name: sumologic-guardduty-benchmark
    LicenseUrl: s3://appdevstore/guarddutybenchmark/v1.0.10/cac1a6df52c685e0f6ebe4ae72078c80
    ReadmeUrl: s3://appdevstore/guarddutybenchmark/v1.0.10/cab012d7fb7887671b751e6f5c0d2062
    SemanticVersion: 1.0.10
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda/tree/master/cloudwatchevents/guarddutybenchmark
Parameters:
  CollectorName:
    Type: String
    Default: GuarddutyCollector
  SourceName:
    Type: String
    Default: GuarddutyEvents
  SourceCategoryName:
    Type: String
    Default: Labs/AWS/Guardduty
  SumoAccessID:
    Type: String
  SumoAccessKey:
    Type: String
  SumoDeployment:
    Type: String
    AllowedValues:
    - au
    - ca
    - de
    - eu
    - jp
    - us2
    - us1
    - in
    - fed
    Description: Enter au, ca, de, eu, jp, us2, or us1
  RemoveSumoResourcesOnDeleteStack:
    AllowedValues:
    - true
    - false
    Default: false
    Description: To delete collector, sources and app when stack is deleted, set this
      parameter to true. Default is false.
    Type: String
Resources:
  CloudWatchEventFunction:
    Properties:
      CodeUri: s3://appdevstore/guarddutybenchmark/v1.0.10/0d13904d1fbd69ecd879992058f1aa41
      Environment:
        Variables:
          SUMO_ENDPOINT:
            Fn::GetAtt:
            - SumoHTTPSource
            - SUMO_ENDPOINT
      Events:
        CloudWatchEventTrigger:
          Properties:
            Pattern:
              source:
              - aws.guardduty
          Type: CloudWatchEvent
      Handler: cloudwatchevents.handler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  SumoAppUtils:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-app-utils
        SemanticVersion: 1.0.24
  SumoHostedCollector:
    Type: Custom::Collector
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Outputs.SumoAppUtilsFunction
      Region:
        Ref: AWS::Region
      CollectorType: Hosted
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      CollectorName:
        Ref: CollectorName
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
  SumoHTTPSource:
    Type: Custom::HTTPSource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Outputs.SumoAppUtilsFunction
      Region:
        Ref: AWS::Region
      SourceName:
        Ref: SourceName
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      SourceCategory:
        Ref: SourceCategoryName
      CollectorId:
        Fn::GetAtt:
        - SumoHostedCollector
        - COLLECTOR_ID
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
      DateFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      DateLocatorRegex: .*"updatedAt":"(.*)".*
  SumoGuardDutyBenchmarkApp:
    Type: Custom::App
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - SumoAppUtils
        - Outputs.SumoAppUtilsFunction
      Region:
        Ref: AWS::Region
      AppName: Amazon GuardDuty Benchmark
      AppId: 8e7efcb3-040a-4a92-9f8d-922fafb24afb
      RemoveOnDeleteStack:
        Ref: RemoveSumoResourcesOnDeleteStack
      AppSources:
        gdbenchmark:
          Fn::Sub: _sourceCategory=${SourceCategoryName}
      SumoAccessID:
        Ref: SumoAccessID
      SumoAccessKey:
        Ref: SumoAccessKey
      SumoDeployment:
        Ref: SumoDeployment
Outputs:
  CloudWatchEventFunction:
    Description: CloudWatchEvent Processor Function ARN
    Value:
      Fn::GetAtt:
      - CloudWatchEventFunction
      - Arn
  GuarddutyBenchmarkAppFolder:
    Description: Folder Name
    Value:
      Fn::GetAtt:
      - SumoGuardDutyBenchmarkApp
      - APP_FOLDER_NAME
